# Generated by Django 3.1.2 on 2020-11-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_administrator', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('adn_id', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('a_email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('a_phone', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='null', max_length=10)),
                ('dob', models.DateField(null=True)),
                ('join', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
