# Generated by Django 3.1.2 on 2020-11-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201105_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='join',
            field=models.DateField(null=True),
        ),
    ]
