# Generated by Django 3.1.2 on 2020-11-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201105_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adn_id',
            field=models.IntegerField(null=True),
        ),
    ]
