# Generated by Django 3.1.2 on 2020-11-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201105_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='a_phone',
            new_name='alternate_phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='a_email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='alternate_email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
