# Generated by Django 3.1.2 on 2020-11-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201122_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adn_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
