# Generated by Django 3.1.2 on 2020-11-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201122_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adn_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
